Added regex taggable filter
osmlab/atlas pull request #677
Opened 2020-09-14 13:31 UTC by mm-ciub

### Description:

During the extension of the **`InvalidTagsCheck`** from atlas-checks arose the need to validate certain tags based on regex patterns instead of tag-value combination. For a specific example, the check had to be extended to verify if source tags contain illegal values, like private company names. 

For this purpose, the **`RegexTaggableFilter`** similarly extends **`Predicate<Taggable>`** and checks if a set of given tag names match at least one pattern from a set of regex patterns and are not an exception to the general rule.

### Potential Impact:

This would not break backwards compatibility. Atlas-checks will have access to the new filter.

### Unit Test Approach:

The filter has been tested with:
- simple configuration containing just a tag and pattern with true and false cases
- extended configuration containing a set of tags and a set of patterns where either none, some or all should match 
- exception configuration with extended configuration where a matched case was also an exception
- tested the method returning the tag names that matched the patterns by comparing with the expected String

### Test Results:

Tested integration with the atlas-checks plugin using the bad source tag flow described above with positive results.

------

2020-09-18 21:15 UTC, lucaspcram approved these changes
Love it, and nice tests! @matthieun ?

2020-09-22 00:07 UTC, matthieun requested changes
This is a great addition, thanks for your contribution @mm-ciub!
Just a few cosmetic suggestions.. If you'd rather keep as-is, that is fine too, and we can approve/merge.
Next step we can update the `ConfiguredFilter` to take the options for a regex filter using that class!

2020-09-22 00:07 UTC, matthieun commented on src/main/java/org/openstreetmap/atlas/tags/filters/README.md
> +```
```suggestion
```java
```

2020-09-22 00:07 UTC, matthieun commented on src/main/java/org/openstreetmap/atlas/tags/filters/RegexTaggableFilter.java
> +
```suggestion
```

2020-09-22 00:07 UTC, matthieun commented on src/main/java/org/openstreetmap/atlas/tags/filters/RegexTaggableFilter.java
> +
```suggestion
```

2020-09-22 00:07 UTC, matthieun commented on src/test/java/org/openstreetmap/atlas/tags/filters/RegexTaggableFilterTest.java
> +
```suggestion
```

2020-09-22 00:07 UTC, matthieun commented on src/test/java/org/openstreetmap/atlas/tags/filters/RegexTaggableFilterTest.java
> +
```suggestion
```

2020-09-24 17:25 UTC, matthieun approved these changes

2020-09-24 17:39 UTC, merged