Atlas command to itemize country boundary map
osmlab/atlas pull request #695
Opened 2020-10-07 22:50 UTC by matthieun

### Description:

This is a new `atlas` command which reads in a boundary file and then saves each individual country as a wkt and geojson file, within the same folder.

Example:

```bash
atlas boundary-itemizer --boundary=/Path/to/boundary.txt.gz
```

### Potential Impact:

None, new command

### Unit Test Approach:

Added one unit test

### Test Results:

Pass

------

In doubt: [Contributing Guidelines](CONTRIBUTING.md)

2020-10-07 22:57 UTC, adahn6 commented on src/main/java/org/openstreetmap/atlas/geography/boundary/CountryBoundaryMapPrinter.java
> + * @deprecated Use CountryBoundaryMapPrinterCommand within the atlas-shell-tools utility instead:
🎉

2020-10-07 22:58 UTC, adahn6 approved these changes

2020-10-08 15:28 UTC, lucaspcram requested changes
Looks great, just a few requests.

2020-10-08 15:28 UTC, lucaspcram commented on src/main/resources/org/openstreetmap/atlas/utilities/command/subcommands/CountryBoundaryMapPrinterCommandExamplesSection.txt
> +#$ boundary-itemizer --boundary=/Users/example/path/to/boundary.txt.gz
`--country-boundary`

2020-10-08 15:28 UTC, lucaspcram commented on src/test/java/org/openstreetmap/atlas/utilities/command/subcommands/CountryBoundaryMapPrinterCommandTest.java
> +    public void testCommandWithInputFile()
Beautiful.

2020-10-09 16:23 UTC, matthieun commented
I will argue this is ready despite the 3 code smells which are related to duplicated code which is contained in a class that is deprecated. The other one is about the deprecation itself.

2020-10-09 16:32 UTC, lucaspcram approved these changes

2020-10-09 16:33 UTC, merged